//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasStationProject.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GasStationProject.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0}を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string E0001 {
            get {
                return ResourceManager.GetString("E0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1} 文字以内で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string E0002 {
            get {
                return ResourceManager.GetString("E0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データが存在しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string E0003 {
            get {
                return ResourceManager.GetString("E0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データが存在していません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string E0004 {
            get {
                return ResourceManager.GetString("E0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} が失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string E0005 {
            get {
                return ResourceManager.GetString("E0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除したの行を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string E0006 {
            get {
                return ResourceManager.GetString("E0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は有効な数字を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string E0007 {
            get {
                return ResourceManager.GetString("E0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が存在していません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string E0008 {
            get {
                return ResourceManager.GetString("E0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   方書以外はすべて入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string E0009 {
            get {
                return ResourceManager.GetString("E0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   電話番号、携帯番号どちらかは必ず入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string E0010 {
            get {
                return ResourceManager.GetString("E0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string I0001 {
            get {
                return ResourceManager.GetString("I0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string I0002 {
            get {
                return ResourceManager.GetString("I0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string I0003 {
            get {
                return ResourceManager.GetString("I0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string I0004 {
            get {
                return ResourceManager.GetString("I0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string I0005 {
            get {
                return ResourceManager.GetString("I0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string I0006 {
            get {
                return ResourceManager.GetString("I0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string I0007 {
            get {
                return ResourceManager.GetString("I0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string I0008 {
            get {
                return ResourceManager.GetString("I0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string I0009 {
            get {
                return ResourceManager.GetString("I0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string I0010 {
            get {
                return ResourceManager.GetString("I0010", resourceCulture);
            }
        }
    }
}
